server:
  port: 9010

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/post_db?allowPublicKeyRetrieval=true&useSSL=false
    username: woorinpang_user
    password: woorinpang_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true

file:
  directory: ${app.home:${user.home}}/workspace/github/woorinpang/attach
  url: http://${file.hostname:localhost}:8080
messages:
  directory: ${file.directory}/messages

